apiVersion: apps/v1	
kind: Deployment
metadata:	
  name: hstakeover-deployment
spec:	
  replicas: 2	
  selector:	
    matchLabels:
      app.kubernetes.io/name: hstakeover-deployment
  template:
    metadata:	
      labels:	
         app.kubernetes.io/name: hstakeover-deployment
    spec:
      containers:
      - name: hso-takeover
        image: bumjin/hso-takeover-project:0.0.1-SNAPSHOT
