apiVersion: v1
kind: Service
metadata:
  name: hstakeover-svc
spec:
  selector:
    app.kubernetes.io/name: hstakeover-deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31604

